name: Code coverage

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.14]
    steps:
      - name: Checkout Triton repository
        uses: actions/checkout@v6

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Triton dependencies
        uses: ./.github/actions/install-triton-deps/linux
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install lcov
        run: |
          sudo apt-get install -y lcov

      - name: Compile Triton
        run: |
          cmake -B build \
                -DGCOV=ON \
                -DZ3_INTERFACE=ON \
                -DZ3_INCLUDE_DIRS=${{ env.Z3_INCLUDE_DIRS }} \
                -DZ3_LIBRARIES=${{ env.Z3_LIBRARIES }} \
                -DBITWUZLA_INTERFACE=ON \
                -DBITWUZLA_INCLUDE_DIRS=${{ env.BITWUZLA_INCLUDE_DIRS }} \
                -DBITWUZLA_LIBRARIES=${{ env.BITWUZLA_LIBRARIES }} \
                -DLLVM_INTERFACE=ON \
                -DCMAKE_PREFIX_PATH=${{ env.LLVM_PATH }} \
                -DCAPSTONE_INCLUDE_DIRS=${{ env.CAPSTONE_INCLUDE_DIRS }} \
                -DCAPSTONE_LIBRARIES=${{ env.CAPSTONE_LIBRARIES }}
          cmake --build build --config Release --parallel
          cmake --install build --config Release --prefix install

      - name: Run tests
        run: |
          make -C build check
          bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
