name: Tests on macOS

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13', '3.14']
    steps:
      - name: Checkout Triton repository
        uses: actions/checkout@v6

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Triton dependencies
        uses: ./.github/actions/install-triton-deps/macos
        with:
          python-version: ${{ matrix.python-version }}

      - name: Compile Triton
        run: |
          mkdir ./build
          cd ./build
          cmake -DZ3_INTERFACE=ON \
                -DZ3_INCLUDE_DIRS=${{ env.Z3_INCLUDE_DIRS }} \
                -DZ3_LIBRARIES=${{ env.Z3_LIBRARIES }} \
                -DBITWUZLA_INTERFACE=ON \
                -DBITWUZLA_INCLUDE_DIRS=${{ env.BITWUZLA_INCLUDE_DIRS }} \
                -DBITWUZLA_LIBRARIES=${{ env.BITWUZLA_LIBRARIES }} \
                -DLLVM_INTERFACE=ON \
                -DCMAKE_PREFIX_PATH=${{ env.LLVM_PATH }} \
                -DBOOST_INTERFACE=OFF ..
          sudo make -j$(sysctl -n hw.ncpu) install

      - name: Run tests
        run: |
          DYLD_LIBRARY_PATH=${{ env.DYLD_LIBRARY_PATH }}:/usr/local/lib ctest --test-dir build --output-on-failure
